### ISSUE TITLE
Can't communicate between shields

### ISSUE THREAD

**Issue by LasaleFamine** [open-electronics/LoRa#7]
I'm trying to communicate between two shields using the basic examples of the libraries (which I found at the end). 

The result is not the expected:
<img width="1111" alt="screen shot 2018-07-12 at 09 19 34" src="https://user-images.githubusercontent.com/13070349/42618319-ee7cdf40-85b4-11e8-86d0-eaaad5fb46ad.png">

I'm trying LoRaTxAddressing on one Arduino+Shield and LoRaRxAddressing on another one. As you can see I can't receive the message on the other board. I have also tried switching the sketches but with no results.

I'm missing something here?

Thank you in advance!

**Comment by danieledenaro** [comment]
I need to know if your system works, before investigate about example you report. So, I suggest that you use basic example with node class (the most recent development). For example use PoledDev and PollingServer coupled examples. If this test doesn't work we can axamine what is wrong in your environment. (Old examples should work, but I prefere start with new examples recently verified and using new simplified structure as Node class).

**Comment by LasaleFamine** [comment]
Hi @danieledenaro, thank you for your quick reply.

I have just tested the other new two examples and this is the result (test with both shields, switching also the sketches):
<img width="1188" alt="screen shot 2018-07-12 at 11 11 29" src="https://user-images.githubusercontent.com/13070349/42623953-7a9933fc-85c4-11e8-9a24-289964900b47.png">

I have modified only the range of `maxdevices` just because I have only two device right now, but the examples are untouched.

**Comment by danieledenaro** [comment]
**Frequence 1024 IMPOSSIBLE**!!! Default is 433.6 MHz. Have you chenged frequence? You can but just in a short range and in any case not more 525 MHz because module type!
LoRa module used (RFM98 or equivalent SX1278) is based on classical 433 MHz band (even if can sintonize frequence from 137 to 525 MHz).

**Comment by LasaleFamine** [comment]
I have just loaded the sketch changing the maxdevices value. Do you think can be something about hardware misconfigured?

**Comment by danieledenaro** [comment]
You have to give me more information about your system (everithing hardware and software). 
For example  LoRa shield or Maduino (what model of shield: new or old). Where and when have you downloaded library. What PC system are you used for Arduino IDE? Etc.
This strange value of frequence is really impossible.
In any case please verify source of LoraNode.h and LoraNode.cpp (about frequence assignment).
Note: look about pin 9 (not have to be used) and open all jumpers.

**Comment by LasaleFamine** [comment]
In order:

- *SHIELD* -> this is the shield (and the guide) used to setup Arduino: [lora-shield.pdf](https://github.com/open-electronics/LoRa/files/2188857/lora-shield.pdf)
- *LIBRARY* -> latest available on GitHub releases
- *OS* -> Windows 10
- *ARDUINO* -> Arduino Uno / Genuino

I have verified the freq assignment but it's ok at 433.6.

I will check out again the setup of the shield, but I really can't understand why this strange value is showing.

**Comment by danieledenaro** [comment]
So, you have old LoRa shield. Open every jump except JCS selecting D10.
In this configuration I have this result (right now with old shield):
![server](https://user-images.githubusercontent.com/11030625/42641062-fb6d4840-85f3-11e8-9234-9330a83e5573.jpg)

Sketch: PollinServer.ino Library: V3.0

**Comment by danieledenaro** [comment]
Just another point. I note that you have also a power setting to 100mW. This is not the default. So you have changed setting or you have software copied from different repository. Please download library from this node and try again in a clean environment..

**Comment by LasaleFamine** [comment]
Hi @danieledenaro, sorry for the delay.

Here is how we changed the switches:
![shield-lora](https://user-images.githubusercontent.com/13070349/42724030-09c96ebe-876b-11e8-9b6b-1f223a071bd2.jpg)

After closing the D10 now the example scripts can't find the LoRa shield and we receive a "No LoRa shield detected" error. 

Do you know why this happens? Opening the D10 will make the shield working again.

**Comment by LasaleFamine** [comment]
UPDATE!

Found the issue: USB alimentation. 

Working with two Arduino through USB won't make work one of the two boards because a drop of power supply. Also note, the D10 jumper made the trick about the frequence and now we have both working (one through 5V power supply and one though PC USB) on 433.6 and 5.00 mW of transmit power.

Thank you so much for the support, really appreciated!

**Comment by danieledenaro** [comment]
OK. So the problem was about SPI transmission noise arised because 5V power not constant. Wasn't it?
I'm glad that everithing works now. 
Suggestion: when I need to see two console output from two Arduino boards I use a powered USB hub.

**Comment by LasaleFamine** [comment]
> OK. So the problem was about SPI transmission noise arised because 5V power not constant. Wasn't it?

Absolutely, just a power supply problem due to poor PC USBs. I didn't think it would be a problem also because I have never worked with two Arduino both attached via USB. 

Anyway, thanks again for the support 👍
